### ISSUE TITLE
[BUG] 提示非法字符

### ISSUE THREAD

**Issue by Evyde** [EugeneJie/AutoEvaluate#1]
## 1.
  
```shell
-----------------------------------------------------------------

请输入您的教学号：xxxxxxxx

请输入您的密码：
(您可能输入了非法字符,密码输入将不能被隐藏,请重新输入：)xxxxx
```
在未输入密码的情况下直接提示非法字符，但是不影响程序的执行。

  
## 2.
`psd_input(text)`这个函数在PyCharm中运行会一直while True，不会退出，建议不要使用getchar这种类似的读字符方法。

具体情况我就不截图了，别人的电脑没有装截图软件。
  
 ---
  
不过有一点我觉得很奇怪，那就是所有的评教都没有要求我输入班级同学的名字。
  
  ---
  
另外，大佬你是哪个年级的啊，真的厉害，正为评教这个事情发愁没想到一上Github就找到了这么好用的软件。

**Comment by EugeneJie** [comment]
抱歉现在才看到，
这个程序最初设计是给同学们直接使用可执行文件的，最终会进行打包（链接地址：https://pan.baidu.com/s/1OV8f1U6uDIBxPmjm3cZXcA ），你提的这两个问题都是在IDE下直接运行才会出现的。pycharm也可以在Run-->Edit Configurations勾选Emulate terminal in output console来解决这个问题。
不用手动输入是因为程序已经自动获取了班级同学的姓名填入，你看一下源码就清楚了
最后，我也不是大佬，就是随便写个程序方便一下大家哈哈，19届的，已经毕业啦

**Comment by Evyde** [comment]
明白了，我以为IDE的运行情况和直接在终端里面运行时一样的。
我没怎么仔细看代码，不过这个自动获取班级同学姓名考虑得很周到啊。
哈哈您还是大佬，我是19级的。

**Comment by Evyde** [comment]
另外今年学校不是搞了个校外vpn么，有没有考虑把走VPN的功能加上呢

**Comment by EugeneJie** [comment]
不知道学校这个vpn什么机制欸，你也可以自己在在源码基础上改一下

**Comment by Evyde** [comment]
[已经有人撸出来网址转换了](https://github.com/MerlynAllen/JLU-VPN)，也是Python写的，直接拿这个就行，都是大佬。。。

**Comment by Evyde** [comment]
还有人直接撸了个[小型HTTP代理程序](https://github.com/Yesterday17/jlu-http-proxy)出来。。。
