### ISSUE TITLE
本项目的许可证

### ISSUE THREAD

**Issue by TechCiel** [EugeneJie/AutoEvaluate#3]
学长你好，自从大作发布以来，评教细则时有变化，虽然您已毕业但仍有同学在不断迭代、改进本程序。能否请您为本项目增加一个开源许可证，GPL 或 MIT 等均可，以便在校同学开发衍生版本？

**Comment by Evyde** [comment]
是啊是啊，没有许可证

**Comment by Evyde** [comment]
程序里有邮箱，要不要发邮件联系一下

**Comment by Evyde** [comment]
> 学长你好，自从大作发布以来，评教细则时有变化，虽然您已毕业但仍有同学在不断迭代、改进本程序。能否请您为本项目增加一个开源许可证，GPL 或 MIT 等均可，以便在校同学开发衍生版本？

我直接在上次PR的时候加了个AGPL 3.0许可证，现在通过了，应该可以开始Fork了:)

**Comment by EugeneJie** [comment]
抱歉，许久没上github，刚留意到，现已通过上面同学提交的PR，感谢小伙伴们对本项目的关注~
